apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nuclear-bot
  name: core-deployment
  labels:
    app: core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-pod
  template:
    metadata:
      name: core-pod
      labels:
        app: core-pod
    spec:
      containers:
        - name: core-pod
          image: vladi15151/nuclear-bot-core:1.1.3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: core-configmap
              mountPath: /etc/config
          env:
            - name: JAVA_OPTS
              value: -Dspring.config.location=file:/etc/config/application.yml
      volumes:
        - name: core-configmap
          configMap:
            name: core-configmap
            items:
              - key: application.yml
                path: application.yml
