apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nuclear-bot
  name: parser-agent-ua-deployment
  labels:
    app: parser-ua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser-ua-pod
  template:
    metadata:
      name: parser-ua-pod
      labels:
        app: parser-ua-pod
    spec:
      containers:
        - name: parser-ua-pod
          image: vladi15151/nuclear-bot-parsing-agent-ua:1.1.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: ua-configmap
              mountPath: /etc/config
          env:
            - name: JAVA_OPTS
              value: -Dspring.config.location=file:/etc/config/application.properties
      volumes:
        - name: ua-configmap
          configMap:
            name: ua-configmap
            items:
              - key: application.properties
                path: application.properties

