apiVersion: v1
kind: Deployment
metadata:
  name: parsing-processor-deployment
  labels:
    app: parsing-processor-deployment
spec:
  template:
    containers:
      - name: parsing-processor
        image: vladi15151/parsing-processor:0.1
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
  selector:
    app: parsing-processor