apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-processor-deployment
  labels:
    app: parsing-processor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parsing-processor-pod
  template:
    metadata:
      name: parsing-processor-pod
      labels:
        app: parsing-processor-pod
    spec:
      containers:
        - name: parsing-processor
          image: vladi15151/parsing-processor:0.3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
