apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nuclear-bot
  name: telegram-deployment
  labels:
    app: telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-pod
  template:
    metadata:
      name: telegram-pod
      labels:
        app: telegram-pod
    spec:
      containers:
        - name: telegram-pod
          image: vladi15151/nuclear-bot-telegram:0.0.1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: -Dspring.config.location=file:/etc/config/application.yml
          volumeMounts:
            - name: telegram-configmap
              mountPath: /etc/config
      volumes:
        - name: telegram-configmap
          configMap:
            name: telegram-configmap
            items:
              - key: application.yml
                path: application.yml


