apiVersion: v1
kind: Service
metadata:
  namespace: nuclear-bot
  name: core-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30124
  selector:
    app: core-pod