apiVersion: v1
kind: Service
metadata:
  name: health-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8888
      nodePort: 30123
  selector:
    app: health-app-pod