apiVersion: v1
kind: Service
metadata:
  name: parsing-processor-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
      nodePort: 30124
  selector:
    app: parsing-processor-pod