apiVersion: v1
kind: Service
metadata:
  namespace: nuclear-bot
  name: parser-ua-service
  labels:
    app: parser-ua-service
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 8080
      nodePort: 30125
  selector:
    app: parser-ua-pod