apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-26T22:32:01Z"
  namespace: nuclear-bot
  name: telegram-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30127
  selector:
    app: telegram-pod