# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: postgresdb
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      # Убрали securityContext и initContainers для Windows
      containers:
      - name: postgresdb
        image: postgres
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: db-secret-credentials
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
      volumes:
        - name: db-data
          hostPath:
            path: /run/desktop/mnt/host/c/data/db/postgres-data  # Путь с поддиректорией
            type: DirectoryOrCreate  # Автоматическое создание