# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: postgresdb
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: postgresdb
    spec:
      volumes:
#        Имя совпадает с именем маунта ниже в разделе volumeMounts
        - name: postgres-data-gce
          gcePersistentDisk:
#            Имя созданного диска на файловой системе командой gcloud compute disks create --size=1GiB --zone=europe-west1-b postgres-gce-disk
            pdName: postgres-gce-disk
            fsType: ext4
      containers:
        # The container name to execute pods
        - name: postgresdb
          # pull postgresimage from docker hub
          image: postgres
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: db-secret-credentials
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-gce

      # Volumes attached to the pod
#      volumes:
#        - name: db-data
#          persistentVolumeClaim:
#            # reference the PersistentVolumeClaim
#            claimName: db-persistent-volume-claim