apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  # Name the persistent chain
  name: postgresdb-persistent-volume
  # Labels for identifying PV
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: local-storage
  capacity:
    # PV Storage capacity
    storage: 1Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # Specify the path to persistent the volumes
  hostPath:
    path: "C:/data/db"
  volumeMode: Filesystem