apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: pgadmin
  POSTGRES_PASSWORD: pgadmin
  POSTGRES_INITDB_ARGS: "--no-locale --encoding=UTF8"