apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: docker-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Должен соответствовать размеру PV
  volumeName: postgres-pv