apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: core-service
                port:
                  number: 80
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: health-app-service
                port:
                  number: 80
          - path: /jsonrpc
            pathType: Prefix
            backend:
              service:
                name: core-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-service # Название вашего Kafka-сервиса
                port:
                  number: 30092 # Название порта, используемого для Kafka
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-service # Название вашего Kafka-сервиса
                port:
                  name: kafka-port # Название порта, используемого для Kafka
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-service # Название вашего Kafka-сервиса
                port:
                  number: 9092 # Название порта, используемого для Kafka
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zookeeper-service
                port:
                  name: zookeeper-port4
