apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-28T12:25:06Z"
  name: core-configmap
  namespace: nuclear-bot
  resourceVersion: "5146855"
  uid: e02e8499-db1e-4419-a7ef-c65a6f0bbb6f
data:
  application.yml: |-
    server:
      port: 8080
    logging:
      level:
        nuclear.bot.core: TRACE
        spring.framework: TRACE
    notification:
      level: INFO
    spring:
      kafka:
        template:
          default-topic: parser-event
        consumer:
          bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: nuclear.bot.core.config.MessageAdapter
          group-id: core
          properties:
            key-class: java.lang.String
            value-class: nuclear.bot.core.dto.AgentMessage
      jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      datasource:
        url: jdbc:postgresql://postgresdb.postgresql.svc.cluster.local:5432/nuclear?useSSL=false
        username: pgadmin
        password: pgadmin
        driver-class-name: org.postgresql.Driver
      flyway:
        create-schemas: true
        schemas: public
        baseline-version: 1
        url: jdbc:postgresql://postgresdb.postgresql.svc.cluster.local:5432/nuclear?useSSL=false
        user: pgadmin
        password: pgadmin
        enabled: true
        locations: classpath:db/migration
        driver-class-name: org.postgresql.Driver
    application:
      name: vlad
      scheduleTime: 60000
