apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram-configmap
  namespace: nuclear-bot
  resourceVersion: "5147973"
  uid: e02e8499-db1e-4419-a7ef-cf5a6f1ccc9a
data:
  application.yml: |-
    bot:
      username: nuclear-bot
      token: 6644705467:AAGB3_pbbn41lGzfbWwI6xBIT3kWYGbyGE0
    server:
      port: 8080
    spring:
      jpa:
        show-sql: true
        database: POSTGRESQL
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      datasource:
        username: pgadmin
        password: pgadmin
        url: jdbc:postgresql://postgresdb.postgresql.svc.cluster.local:5432/nuclear?useSSL=false
        driver-class-name: org.postgresql.Driver