apiVersion: v1
kind: Pod
metadata:
  name: health-app-pod
  labels:
    app: health-app-pod
spec:
  containers:
    - image: vladi15151/nuclear-bot-health-service:0.3
      name: health-app-pod
      ports:
        - name: http
          containerPort: 8888
          protocol: TCP