apiVersion: v1
kind: Pod
metadata:
  name: parsing-processor
  labels:
    app: parsing-processor
spec:
  containers:
    - name: parsing-processor
      image: vladi15151/parsing-processor:0.2
      ports:
        - name: http
          containerPort: 80
          protocol: TCP